// get
// listInvites
// createInvite
// list
// listMyInvites
// create
// getInviteDetails
// acceptOrDeclineInvite
// deleteInvite
// delete
// createComment
// listComments
// updateComment
// deleteComment
// update
// createLocation
// updateLocation
// deleteLocation
