/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignInIndexRouteImport } from './routes/sign-in/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardUsersIndexRouteImport } from './routes/dashboard/users/index'
import { Route as DashboardReportsIndexRouteImport } from './routes/dashboard/reports/index'
import { Route as DashboardPlacesIndexRouteImport } from './routes/dashboard/places/index'
import { Route as DashboardCitiesIndexRouteImport } from './routes/dashboard/cities/index'
import { Route as DashboardCategoriesIndexRouteImport } from './routes/dashboard/categories/index'
import { Route as DashboardAccoladesIndexRouteImport } from './routes/dashboard/accolades/index'
import { Route as DashboardPlacesNewRouteImport } from './routes/dashboard/places/new'
import { Route as DashboardCitiesNewRouteImport } from './routes/dashboard/cities/new'
import { Route as DashboardCategoriesNewRouteImport } from './routes/dashboard/categories/new'
import { Route as DashboardAccoladesNewRouteImport } from './routes/dashboard/accolades/new'
import { Route as DashboardUsersIdIndexRouteImport } from './routes/dashboard/users/$id/index'
import { Route as DashboardReportsIdIndexRouteImport } from './routes/dashboard/reports/$id/index'
import { Route as DashboardPlacesIdIndexRouteImport } from './routes/dashboard/places/$id/index'
import { Route as DashboardCitiesIdIndexRouteImport } from './routes/dashboard/cities/$id/index'
import { Route as DashboardCategoriesIdIndexRouteImport } from './routes/dashboard/categories/$id/index'
import { Route as DashboardAccoladesIdIndexRouteImport } from './routes/dashboard/accolades/$id/index'
import { Route as DashboardPlacesIdEditRouteImport } from './routes/dashboard/places/$id/edit'
import { Route as DashboardCitiesIdEditRouteImport } from './routes/dashboard/cities/$id/edit'
import { Route as DashboardCategoriesIdEditRouteImport } from './routes/dashboard/categories/$id/edit'
import { Route as DashboardAccoladesIdEditRouteImport } from './routes/dashboard/accolades/$id/edit'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInIndexRoute = SignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersIndexRoute = DashboardUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsIndexRoute = DashboardReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlacesIndexRoute = DashboardPlacesIndexRouteImport.update({
  id: '/places/',
  path: '/places/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCitiesIndexRoute = DashboardCitiesIndexRouteImport.update({
  id: '/cities/',
  path: '/cities/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCategoriesIndexRoute =
  DashboardCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAccoladesIndexRoute = DashboardAccoladesIndexRouteImport.update({
  id: '/accolades/',
  path: '/accolades/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlacesNewRoute = DashboardPlacesNewRouteImport.update({
  id: '/places/new',
  path: '/places/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCitiesNewRoute = DashboardCitiesNewRouteImport.update({
  id: '/cities/new',
  path: '/cities/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCategoriesNewRoute = DashboardCategoriesNewRouteImport.update({
  id: '/categories/new',
  path: '/categories/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccoladesNewRoute = DashboardAccoladesNewRouteImport.update({
  id: '/accolades/new',
  path: '/accolades/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersIdIndexRoute = DashboardUsersIdIndexRouteImport.update({
  id: '/users/$id/',
  path: '/users/$id/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsIdIndexRoute = DashboardReportsIdIndexRouteImport.update({
  id: '/reports/$id/',
  path: '/reports/$id/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlacesIdIndexRoute = DashboardPlacesIdIndexRouteImport.update({
  id: '/places/$id/',
  path: '/places/$id/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCitiesIdIndexRoute = DashboardCitiesIdIndexRouteImport.update({
  id: '/cities/$id/',
  path: '/cities/$id/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCategoriesIdIndexRoute =
  DashboardCategoriesIdIndexRouteImport.update({
    id: '/categories/$id/',
    path: '/categories/$id/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAccoladesIdIndexRoute =
  DashboardAccoladesIdIndexRouteImport.update({
    id: '/accolades/$id/',
    path: '/accolades/$id/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPlacesIdEditRoute = DashboardPlacesIdEditRouteImport.update({
  id: '/places/$id/edit',
  path: '/places/$id/edit',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCitiesIdEditRoute = DashboardCitiesIdEditRouteImport.update({
  id: '/cities/$id/edit',
  path: '/cities/$id/edit',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCategoriesIdEditRoute =
  DashboardCategoriesIdEditRouteImport.update({
    id: '/categories/$id/edit',
    path: '/categories/$id/edit',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAccoladesIdEditRoute =
  DashboardAccoladesIdEditRouteImport.update({
    id: '/accolades/$id/edit',
    path: '/accolades/$id/edit',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/sign-in/': typeof SignInIndexRoute
  '/dashboard/accolades/new': typeof DashboardAccoladesNewRoute
  '/dashboard/categories/new': typeof DashboardCategoriesNewRoute
  '/dashboard/cities/new': typeof DashboardCitiesNewRoute
  '/dashboard/places/new': typeof DashboardPlacesNewRoute
  '/dashboard/accolades/': typeof DashboardAccoladesIndexRoute
  '/dashboard/categories/': typeof DashboardCategoriesIndexRoute
  '/dashboard/cities/': typeof DashboardCitiesIndexRoute
  '/dashboard/places/': typeof DashboardPlacesIndexRoute
  '/dashboard/reports/': typeof DashboardReportsIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexRoute
  '/dashboard/accolades/$id/edit': typeof DashboardAccoladesIdEditRoute
  '/dashboard/categories/$id/edit': typeof DashboardCategoriesIdEditRoute
  '/dashboard/cities/$id/edit': typeof DashboardCitiesIdEditRoute
  '/dashboard/places/$id/edit': typeof DashboardPlacesIdEditRoute
  '/dashboard/accolades/$id/': typeof DashboardAccoladesIdIndexRoute
  '/dashboard/categories/$id/': typeof DashboardCategoriesIdIndexRoute
  '/dashboard/cities/$id/': typeof DashboardCitiesIdIndexRoute
  '/dashboard/places/$id/': typeof DashboardPlacesIdIndexRoute
  '/dashboard/reports/$id/': typeof DashboardReportsIdIndexRoute
  '/dashboard/users/$id/': typeof DashboardUsersIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/sign-in': typeof SignInIndexRoute
  '/dashboard/accolades/new': typeof DashboardAccoladesNewRoute
  '/dashboard/categories/new': typeof DashboardCategoriesNewRoute
  '/dashboard/cities/new': typeof DashboardCitiesNewRoute
  '/dashboard/places/new': typeof DashboardPlacesNewRoute
  '/dashboard/accolades': typeof DashboardAccoladesIndexRoute
  '/dashboard/categories': typeof DashboardCategoriesIndexRoute
  '/dashboard/cities': typeof DashboardCitiesIndexRoute
  '/dashboard/places': typeof DashboardPlacesIndexRoute
  '/dashboard/reports': typeof DashboardReportsIndexRoute
  '/dashboard/users': typeof DashboardUsersIndexRoute
  '/dashboard/accolades/$id/edit': typeof DashboardAccoladesIdEditRoute
  '/dashboard/categories/$id/edit': typeof DashboardCategoriesIdEditRoute
  '/dashboard/cities/$id/edit': typeof DashboardCitiesIdEditRoute
  '/dashboard/places/$id/edit': typeof DashboardPlacesIdEditRoute
  '/dashboard/accolades/$id': typeof DashboardAccoladesIdIndexRoute
  '/dashboard/categories/$id': typeof DashboardCategoriesIdIndexRoute
  '/dashboard/cities/$id': typeof DashboardCitiesIdIndexRoute
  '/dashboard/places/$id': typeof DashboardPlacesIdIndexRoute
  '/dashboard/reports/$id': typeof DashboardReportsIdIndexRoute
  '/dashboard/users/$id': typeof DashboardUsersIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/sign-in/': typeof SignInIndexRoute
  '/dashboard/accolades/new': typeof DashboardAccoladesNewRoute
  '/dashboard/categories/new': typeof DashboardCategoriesNewRoute
  '/dashboard/cities/new': typeof DashboardCitiesNewRoute
  '/dashboard/places/new': typeof DashboardPlacesNewRoute
  '/dashboard/accolades/': typeof DashboardAccoladesIndexRoute
  '/dashboard/categories/': typeof DashboardCategoriesIndexRoute
  '/dashboard/cities/': typeof DashboardCitiesIndexRoute
  '/dashboard/places/': typeof DashboardPlacesIndexRoute
  '/dashboard/reports/': typeof DashboardReportsIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexRoute
  '/dashboard/accolades/$id/edit': typeof DashboardAccoladesIdEditRoute
  '/dashboard/categories/$id/edit': typeof DashboardCategoriesIdEditRoute
  '/dashboard/cities/$id/edit': typeof DashboardCitiesIdEditRoute
  '/dashboard/places/$id/edit': typeof DashboardPlacesIdEditRoute
  '/dashboard/accolades/$id/': typeof DashboardAccoladesIdIndexRoute
  '/dashboard/categories/$id/': typeof DashboardCategoriesIdIndexRoute
  '/dashboard/cities/$id/': typeof DashboardCitiesIdIndexRoute
  '/dashboard/places/$id/': typeof DashboardPlacesIdIndexRoute
  '/dashboard/reports/$id/': typeof DashboardReportsIdIndexRoute
  '/dashboard/users/$id/': typeof DashboardUsersIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/sign-in/'
    | '/dashboard/accolades/new'
    | '/dashboard/categories/new'
    | '/dashboard/cities/new'
    | '/dashboard/places/new'
    | '/dashboard/accolades/'
    | '/dashboard/categories/'
    | '/dashboard/cities/'
    | '/dashboard/places/'
    | '/dashboard/reports/'
    | '/dashboard/users/'
    | '/dashboard/accolades/$id/edit'
    | '/dashboard/categories/$id/edit'
    | '/dashboard/cities/$id/edit'
    | '/dashboard/places/$id/edit'
    | '/dashboard/accolades/$id/'
    | '/dashboard/categories/$id/'
    | '/dashboard/cities/$id/'
    | '/dashboard/places/$id/'
    | '/dashboard/reports/$id/'
    | '/dashboard/users/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/sign-in'
    | '/dashboard/accolades/new'
    | '/dashboard/categories/new'
    | '/dashboard/cities/new'
    | '/dashboard/places/new'
    | '/dashboard/accolades'
    | '/dashboard/categories'
    | '/dashboard/cities'
    | '/dashboard/places'
    | '/dashboard/reports'
    | '/dashboard/users'
    | '/dashboard/accolades/$id/edit'
    | '/dashboard/categories/$id/edit'
    | '/dashboard/cities/$id/edit'
    | '/dashboard/places/$id/edit'
    | '/dashboard/accolades/$id'
    | '/dashboard/categories/$id'
    | '/dashboard/cities/$id'
    | '/dashboard/places/$id'
    | '/dashboard/reports/$id'
    | '/dashboard/users/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/sign-in/'
    | '/dashboard/accolades/new'
    | '/dashboard/categories/new'
    | '/dashboard/cities/new'
    | '/dashboard/places/new'
    | '/dashboard/accolades/'
    | '/dashboard/categories/'
    | '/dashboard/cities/'
    | '/dashboard/places/'
    | '/dashboard/reports/'
    | '/dashboard/users/'
    | '/dashboard/accolades/$id/edit'
    | '/dashboard/categories/$id/edit'
    | '/dashboard/cities/$id/edit'
    | '/dashboard/places/$id/edit'
    | '/dashboard/accolades/$id/'
    | '/dashboard/categories/$id/'
    | '/dashboard/cities/$id/'
    | '/dashboard/places/$id/'
    | '/dashboard/reports/$id/'
    | '/dashboard/users/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  SignInIndexRoute: typeof SignInIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/': {
      id: '/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof SignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/users/': {
      id: '/dashboard/users/'
      path: '/users'
      fullPath: '/dashboard/users/'
      preLoaderRoute: typeof DashboardUsersIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports/': {
      id: '/dashboard/reports/'
      path: '/reports'
      fullPath: '/dashboard/reports/'
      preLoaderRoute: typeof DashboardReportsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/places/': {
      id: '/dashboard/places/'
      path: '/places'
      fullPath: '/dashboard/places/'
      preLoaderRoute: typeof DashboardPlacesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cities/': {
      id: '/dashboard/cities/'
      path: '/cities'
      fullPath: '/dashboard/cities/'
      preLoaderRoute: typeof DashboardCitiesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/categories/': {
      id: '/dashboard/categories/'
      path: '/categories'
      fullPath: '/dashboard/categories/'
      preLoaderRoute: typeof DashboardCategoriesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/accolades/': {
      id: '/dashboard/accolades/'
      path: '/accolades'
      fullPath: '/dashboard/accolades/'
      preLoaderRoute: typeof DashboardAccoladesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/places/new': {
      id: '/dashboard/places/new'
      path: '/places/new'
      fullPath: '/dashboard/places/new'
      preLoaderRoute: typeof DashboardPlacesNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cities/new': {
      id: '/dashboard/cities/new'
      path: '/cities/new'
      fullPath: '/dashboard/cities/new'
      preLoaderRoute: typeof DashboardCitiesNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/categories/new': {
      id: '/dashboard/categories/new'
      path: '/categories/new'
      fullPath: '/dashboard/categories/new'
      preLoaderRoute: typeof DashboardCategoriesNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/accolades/new': {
      id: '/dashboard/accolades/new'
      path: '/accolades/new'
      fullPath: '/dashboard/accolades/new'
      preLoaderRoute: typeof DashboardAccoladesNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/users/$id/': {
      id: '/dashboard/users/$id/'
      path: '/users/$id'
      fullPath: '/dashboard/users/$id/'
      preLoaderRoute: typeof DashboardUsersIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports/$id/': {
      id: '/dashboard/reports/$id/'
      path: '/reports/$id'
      fullPath: '/dashboard/reports/$id/'
      preLoaderRoute: typeof DashboardReportsIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/places/$id/': {
      id: '/dashboard/places/$id/'
      path: '/places/$id'
      fullPath: '/dashboard/places/$id/'
      preLoaderRoute: typeof DashboardPlacesIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cities/$id/': {
      id: '/dashboard/cities/$id/'
      path: '/cities/$id'
      fullPath: '/dashboard/cities/$id/'
      preLoaderRoute: typeof DashboardCitiesIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/categories/$id/': {
      id: '/dashboard/categories/$id/'
      path: '/categories/$id'
      fullPath: '/dashboard/categories/$id/'
      preLoaderRoute: typeof DashboardCategoriesIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/accolades/$id/': {
      id: '/dashboard/accolades/$id/'
      path: '/accolades/$id'
      fullPath: '/dashboard/accolades/$id/'
      preLoaderRoute: typeof DashboardAccoladesIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/places/$id/edit': {
      id: '/dashboard/places/$id/edit'
      path: '/places/$id/edit'
      fullPath: '/dashboard/places/$id/edit'
      preLoaderRoute: typeof DashboardPlacesIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cities/$id/edit': {
      id: '/dashboard/cities/$id/edit'
      path: '/cities/$id/edit'
      fullPath: '/dashboard/cities/$id/edit'
      preLoaderRoute: typeof DashboardCitiesIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/categories/$id/edit': {
      id: '/dashboard/categories/$id/edit'
      path: '/categories/$id/edit'
      fullPath: '/dashboard/categories/$id/edit'
      preLoaderRoute: typeof DashboardCategoriesIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/accolades/$id/edit': {
      id: '/dashboard/accolades/$id/edit'
      path: '/accolades/$id/edit'
      fullPath: '/dashboard/accolades/$id/edit'
      preLoaderRoute: typeof DashboardAccoladesIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAccoladesNewRoute: typeof DashboardAccoladesNewRoute
  DashboardCategoriesNewRoute: typeof DashboardCategoriesNewRoute
  DashboardCitiesNewRoute: typeof DashboardCitiesNewRoute
  DashboardPlacesNewRoute: typeof DashboardPlacesNewRoute
  DashboardAccoladesIndexRoute: typeof DashboardAccoladesIndexRoute
  DashboardCategoriesIndexRoute: typeof DashboardCategoriesIndexRoute
  DashboardCitiesIndexRoute: typeof DashboardCitiesIndexRoute
  DashboardPlacesIndexRoute: typeof DashboardPlacesIndexRoute
  DashboardReportsIndexRoute: typeof DashboardReportsIndexRoute
  DashboardUsersIndexRoute: typeof DashboardUsersIndexRoute
  DashboardAccoladesIdEditRoute: typeof DashboardAccoladesIdEditRoute
  DashboardCategoriesIdEditRoute: typeof DashboardCategoriesIdEditRoute
  DashboardCitiesIdEditRoute: typeof DashboardCitiesIdEditRoute
  DashboardPlacesIdEditRoute: typeof DashboardPlacesIdEditRoute
  DashboardAccoladesIdIndexRoute: typeof DashboardAccoladesIdIndexRoute
  DashboardCategoriesIdIndexRoute: typeof DashboardCategoriesIdIndexRoute
  DashboardCitiesIdIndexRoute: typeof DashboardCitiesIdIndexRoute
  DashboardPlacesIdIndexRoute: typeof DashboardPlacesIdIndexRoute
  DashboardReportsIdIndexRoute: typeof DashboardReportsIdIndexRoute
  DashboardUsersIdIndexRoute: typeof DashboardUsersIdIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAccoladesNewRoute: DashboardAccoladesNewRoute,
  DashboardCategoriesNewRoute: DashboardCategoriesNewRoute,
  DashboardCitiesNewRoute: DashboardCitiesNewRoute,
  DashboardPlacesNewRoute: DashboardPlacesNewRoute,
  DashboardAccoladesIndexRoute: DashboardAccoladesIndexRoute,
  DashboardCategoriesIndexRoute: DashboardCategoriesIndexRoute,
  DashboardCitiesIndexRoute: DashboardCitiesIndexRoute,
  DashboardPlacesIndexRoute: DashboardPlacesIndexRoute,
  DashboardReportsIndexRoute: DashboardReportsIndexRoute,
  DashboardUsersIndexRoute: DashboardUsersIndexRoute,
  DashboardAccoladesIdEditRoute: DashboardAccoladesIdEditRoute,
  DashboardCategoriesIdEditRoute: DashboardCategoriesIdEditRoute,
  DashboardCitiesIdEditRoute: DashboardCitiesIdEditRoute,
  DashboardPlacesIdEditRoute: DashboardPlacesIdEditRoute,
  DashboardAccoladesIdIndexRoute: DashboardAccoladesIdIndexRoute,
  DashboardCategoriesIdIndexRoute: DashboardCategoriesIdIndexRoute,
  DashboardCitiesIdIndexRoute: DashboardCitiesIdIndexRoute,
  DashboardPlacesIdIndexRoute: DashboardPlacesIdIndexRoute,
  DashboardReportsIdIndexRoute: DashboardReportsIdIndexRoute,
  DashboardUsersIdIndexRoute: DashboardUsersIdIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  SignInIndexRoute: SignInIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
