/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignInIndexRouteImport } from './routes/sign-in/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardUsersIndexRouteImport } from './routes/dashboard/users/index'
import { Route as DashboardReportsIndexRouteImport } from './routes/dashboard/reports/index'
import { Route as DashboardPlacesIndexRouteImport } from './routes/dashboard/places/index'
import { Route as DashboardCitiesIndexRouteImport } from './routes/dashboard/cities/index'
import { Route as DashboardCategoriesIndexRouteImport } from './routes/dashboard/categories/index'
import { Route as DashboardUsersIdIndexRouteImport } from './routes/dashboard/users/$id/index'
import { Route as DashboardReportsIdIndexRouteImport } from './routes/dashboard/reports/$id/index'
import { Route as DashboardPlacesNewIndexRouteImport } from './routes/dashboard/places/new/index'
import { Route as DashboardPlacesIdIndexRouteImport } from './routes/dashboard/places/$id/index'
import { Route as DashboardCitiesNewIndexRouteImport } from './routes/dashboard/cities/new/index'
import { Route as DashboardCitiesIdIndexRouteImport } from './routes/dashboard/cities/$id/index'
import { Route as DashboardCategoriesNewIndexRouteImport } from './routes/dashboard/categories/new/index'
import { Route as DashboardCategoriesIdIndexRouteImport } from './routes/dashboard/categories/$id/index'
import { Route as DashboardPlacesIdEditIndexRouteImport } from './routes/dashboard/places/$id/edit/index'
import { Route as DashboardCitiesIdEditIndexRouteImport } from './routes/dashboard/cities/$id/edit/index'
import { Route as DashboardCategoriesIdEditIndexRouteImport } from './routes/dashboard/categories/$id/edit/index'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInIndexRoute = SignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersIndexRoute = DashboardUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsIndexRoute = DashboardReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlacesIndexRoute = DashboardPlacesIndexRouteImport.update({
  id: '/places/',
  path: '/places/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCitiesIndexRoute = DashboardCitiesIndexRouteImport.update({
  id: '/cities/',
  path: '/cities/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCategoriesIndexRoute =
  DashboardCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardUsersIdIndexRoute = DashboardUsersIdIndexRouteImport.update({
  id: '/users/$id/',
  path: '/users/$id/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsIdIndexRoute = DashboardReportsIdIndexRouteImport.update({
  id: '/reports/$id/',
  path: '/reports/$id/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlacesNewIndexRoute = DashboardPlacesNewIndexRouteImport.update({
  id: '/places/new/',
  path: '/places/new/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlacesIdIndexRoute = DashboardPlacesIdIndexRouteImport.update({
  id: '/places/$id/',
  path: '/places/$id/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCitiesNewIndexRoute = DashboardCitiesNewIndexRouteImport.update({
  id: '/cities/new/',
  path: '/cities/new/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCitiesIdIndexRoute = DashboardCitiesIdIndexRouteImport.update({
  id: '/cities/$id/',
  path: '/cities/$id/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCategoriesNewIndexRoute =
  DashboardCategoriesNewIndexRouteImport.update({
    id: '/categories/new/',
    path: '/categories/new/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardCategoriesIdIndexRoute =
  DashboardCategoriesIdIndexRouteImport.update({
    id: '/categories/$id/',
    path: '/categories/$id/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPlacesIdEditIndexRoute =
  DashboardPlacesIdEditIndexRouteImport.update({
    id: '/places/$id/edit/',
    path: '/places/$id/edit/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardCitiesIdEditIndexRoute =
  DashboardCitiesIdEditIndexRouteImport.update({
    id: '/cities/$id/edit/',
    path: '/cities/$id/edit/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardCategoriesIdEditIndexRoute =
  DashboardCategoriesIdEditIndexRouteImport.update({
    id: '/categories/$id/edit/',
    path: '/categories/$id/edit/',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/sign-in/': typeof SignInIndexRoute
  '/dashboard/categories/': typeof DashboardCategoriesIndexRoute
  '/dashboard/cities/': typeof DashboardCitiesIndexRoute
  '/dashboard/places/': typeof DashboardPlacesIndexRoute
  '/dashboard/reports/': typeof DashboardReportsIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexRoute
  '/dashboard/categories/$id/': typeof DashboardCategoriesIdIndexRoute
  '/dashboard/categories/new/': typeof DashboardCategoriesNewIndexRoute
  '/dashboard/cities/$id/': typeof DashboardCitiesIdIndexRoute
  '/dashboard/cities/new/': typeof DashboardCitiesNewIndexRoute
  '/dashboard/places/$id/': typeof DashboardPlacesIdIndexRoute
  '/dashboard/places/new/': typeof DashboardPlacesNewIndexRoute
  '/dashboard/reports/$id/': typeof DashboardReportsIdIndexRoute
  '/dashboard/users/$id/': typeof DashboardUsersIdIndexRoute
  '/dashboard/categories/$id/edit/': typeof DashboardCategoriesIdEditIndexRoute
  '/dashboard/cities/$id/edit/': typeof DashboardCitiesIdEditIndexRoute
  '/dashboard/places/$id/edit/': typeof DashboardPlacesIdEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/sign-in': typeof SignInIndexRoute
  '/dashboard/categories': typeof DashboardCategoriesIndexRoute
  '/dashboard/cities': typeof DashboardCitiesIndexRoute
  '/dashboard/places': typeof DashboardPlacesIndexRoute
  '/dashboard/reports': typeof DashboardReportsIndexRoute
  '/dashboard/users': typeof DashboardUsersIndexRoute
  '/dashboard/categories/$id': typeof DashboardCategoriesIdIndexRoute
  '/dashboard/categories/new': typeof DashboardCategoriesNewIndexRoute
  '/dashboard/cities/$id': typeof DashboardCitiesIdIndexRoute
  '/dashboard/cities/new': typeof DashboardCitiesNewIndexRoute
  '/dashboard/places/$id': typeof DashboardPlacesIdIndexRoute
  '/dashboard/places/new': typeof DashboardPlacesNewIndexRoute
  '/dashboard/reports/$id': typeof DashboardReportsIdIndexRoute
  '/dashboard/users/$id': typeof DashboardUsersIdIndexRoute
  '/dashboard/categories/$id/edit': typeof DashboardCategoriesIdEditIndexRoute
  '/dashboard/cities/$id/edit': typeof DashboardCitiesIdEditIndexRoute
  '/dashboard/places/$id/edit': typeof DashboardPlacesIdEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/sign-in/': typeof SignInIndexRoute
  '/dashboard/categories/': typeof DashboardCategoriesIndexRoute
  '/dashboard/cities/': typeof DashboardCitiesIndexRoute
  '/dashboard/places/': typeof DashboardPlacesIndexRoute
  '/dashboard/reports/': typeof DashboardReportsIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexRoute
  '/dashboard/categories/$id/': typeof DashboardCategoriesIdIndexRoute
  '/dashboard/categories/new/': typeof DashboardCategoriesNewIndexRoute
  '/dashboard/cities/$id/': typeof DashboardCitiesIdIndexRoute
  '/dashboard/cities/new/': typeof DashboardCitiesNewIndexRoute
  '/dashboard/places/$id/': typeof DashboardPlacesIdIndexRoute
  '/dashboard/places/new/': typeof DashboardPlacesNewIndexRoute
  '/dashboard/reports/$id/': typeof DashboardReportsIdIndexRoute
  '/dashboard/users/$id/': typeof DashboardUsersIdIndexRoute
  '/dashboard/categories/$id/edit/': typeof DashboardCategoriesIdEditIndexRoute
  '/dashboard/cities/$id/edit/': typeof DashboardCitiesIdEditIndexRoute
  '/dashboard/places/$id/edit/': typeof DashboardPlacesIdEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/sign-in/'
    | '/dashboard/categories/'
    | '/dashboard/cities/'
    | '/dashboard/places/'
    | '/dashboard/reports/'
    | '/dashboard/users/'
    | '/dashboard/categories/$id/'
    | '/dashboard/categories/new/'
    | '/dashboard/cities/$id/'
    | '/dashboard/cities/new/'
    | '/dashboard/places/$id/'
    | '/dashboard/places/new/'
    | '/dashboard/reports/$id/'
    | '/dashboard/users/$id/'
    | '/dashboard/categories/$id/edit/'
    | '/dashboard/cities/$id/edit/'
    | '/dashboard/places/$id/edit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/sign-in'
    | '/dashboard/categories'
    | '/dashboard/cities'
    | '/dashboard/places'
    | '/dashboard/reports'
    | '/dashboard/users'
    | '/dashboard/categories/$id'
    | '/dashboard/categories/new'
    | '/dashboard/cities/$id'
    | '/dashboard/cities/new'
    | '/dashboard/places/$id'
    | '/dashboard/places/new'
    | '/dashboard/reports/$id'
    | '/dashboard/users/$id'
    | '/dashboard/categories/$id/edit'
    | '/dashboard/cities/$id/edit'
    | '/dashboard/places/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/sign-in/'
    | '/dashboard/categories/'
    | '/dashboard/cities/'
    | '/dashboard/places/'
    | '/dashboard/reports/'
    | '/dashboard/users/'
    | '/dashboard/categories/$id/'
    | '/dashboard/categories/new/'
    | '/dashboard/cities/$id/'
    | '/dashboard/cities/new/'
    | '/dashboard/places/$id/'
    | '/dashboard/places/new/'
    | '/dashboard/reports/$id/'
    | '/dashboard/users/$id/'
    | '/dashboard/categories/$id/edit/'
    | '/dashboard/cities/$id/edit/'
    | '/dashboard/places/$id/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  SignInIndexRoute: typeof SignInIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/': {
      id: '/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof SignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/users/': {
      id: '/dashboard/users/'
      path: '/users'
      fullPath: '/dashboard/users/'
      preLoaderRoute: typeof DashboardUsersIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports/': {
      id: '/dashboard/reports/'
      path: '/reports'
      fullPath: '/dashboard/reports/'
      preLoaderRoute: typeof DashboardReportsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/places/': {
      id: '/dashboard/places/'
      path: '/places'
      fullPath: '/dashboard/places/'
      preLoaderRoute: typeof DashboardPlacesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cities/': {
      id: '/dashboard/cities/'
      path: '/cities'
      fullPath: '/dashboard/cities/'
      preLoaderRoute: typeof DashboardCitiesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/categories/': {
      id: '/dashboard/categories/'
      path: '/categories'
      fullPath: '/dashboard/categories/'
      preLoaderRoute: typeof DashboardCategoriesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/users/$id/': {
      id: '/dashboard/users/$id/'
      path: '/users/$id'
      fullPath: '/dashboard/users/$id/'
      preLoaderRoute: typeof DashboardUsersIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports/$id/': {
      id: '/dashboard/reports/$id/'
      path: '/reports/$id'
      fullPath: '/dashboard/reports/$id/'
      preLoaderRoute: typeof DashboardReportsIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/places/new/': {
      id: '/dashboard/places/new/'
      path: '/places/new'
      fullPath: '/dashboard/places/new/'
      preLoaderRoute: typeof DashboardPlacesNewIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/places/$id/': {
      id: '/dashboard/places/$id/'
      path: '/places/$id'
      fullPath: '/dashboard/places/$id/'
      preLoaderRoute: typeof DashboardPlacesIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cities/new/': {
      id: '/dashboard/cities/new/'
      path: '/cities/new'
      fullPath: '/dashboard/cities/new/'
      preLoaderRoute: typeof DashboardCitiesNewIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cities/$id/': {
      id: '/dashboard/cities/$id/'
      path: '/cities/$id'
      fullPath: '/dashboard/cities/$id/'
      preLoaderRoute: typeof DashboardCitiesIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/categories/new/': {
      id: '/dashboard/categories/new/'
      path: '/categories/new'
      fullPath: '/dashboard/categories/new/'
      preLoaderRoute: typeof DashboardCategoriesNewIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/categories/$id/': {
      id: '/dashboard/categories/$id/'
      path: '/categories/$id'
      fullPath: '/dashboard/categories/$id/'
      preLoaderRoute: typeof DashboardCategoriesIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/places/$id/edit/': {
      id: '/dashboard/places/$id/edit/'
      path: '/places/$id/edit'
      fullPath: '/dashboard/places/$id/edit/'
      preLoaderRoute: typeof DashboardPlacesIdEditIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cities/$id/edit/': {
      id: '/dashboard/cities/$id/edit/'
      path: '/cities/$id/edit'
      fullPath: '/dashboard/cities/$id/edit/'
      preLoaderRoute: typeof DashboardCitiesIdEditIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/categories/$id/edit/': {
      id: '/dashboard/categories/$id/edit/'
      path: '/categories/$id/edit'
      fullPath: '/dashboard/categories/$id/edit/'
      preLoaderRoute: typeof DashboardCategoriesIdEditIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCategoriesIndexRoute: typeof DashboardCategoriesIndexRoute
  DashboardCitiesIndexRoute: typeof DashboardCitiesIndexRoute
  DashboardPlacesIndexRoute: typeof DashboardPlacesIndexRoute
  DashboardReportsIndexRoute: typeof DashboardReportsIndexRoute
  DashboardUsersIndexRoute: typeof DashboardUsersIndexRoute
  DashboardCategoriesIdIndexRoute: typeof DashboardCategoriesIdIndexRoute
  DashboardCategoriesNewIndexRoute: typeof DashboardCategoriesNewIndexRoute
  DashboardCitiesIdIndexRoute: typeof DashboardCitiesIdIndexRoute
  DashboardCitiesNewIndexRoute: typeof DashboardCitiesNewIndexRoute
  DashboardPlacesIdIndexRoute: typeof DashboardPlacesIdIndexRoute
  DashboardPlacesNewIndexRoute: typeof DashboardPlacesNewIndexRoute
  DashboardReportsIdIndexRoute: typeof DashboardReportsIdIndexRoute
  DashboardUsersIdIndexRoute: typeof DashboardUsersIdIndexRoute
  DashboardCategoriesIdEditIndexRoute: typeof DashboardCategoriesIdEditIndexRoute
  DashboardCitiesIdEditIndexRoute: typeof DashboardCitiesIdEditIndexRoute
  DashboardPlacesIdEditIndexRoute: typeof DashboardPlacesIdEditIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCategoriesIndexRoute: DashboardCategoriesIndexRoute,
  DashboardCitiesIndexRoute: DashboardCitiesIndexRoute,
  DashboardPlacesIndexRoute: DashboardPlacesIndexRoute,
  DashboardReportsIndexRoute: DashboardReportsIndexRoute,
  DashboardUsersIndexRoute: DashboardUsersIndexRoute,
  DashboardCategoriesIdIndexRoute: DashboardCategoriesIdIndexRoute,
  DashboardCategoriesNewIndexRoute: DashboardCategoriesNewIndexRoute,
  DashboardCitiesIdIndexRoute: DashboardCitiesIdIndexRoute,
  DashboardCitiesNewIndexRoute: DashboardCitiesNewIndexRoute,
  DashboardPlacesIdIndexRoute: DashboardPlacesIdIndexRoute,
  DashboardPlacesNewIndexRoute: DashboardPlacesNewIndexRoute,
  DashboardReportsIdIndexRoute: DashboardReportsIdIndexRoute,
  DashboardUsersIdIndexRoute: DashboardUsersIdIndexRoute,
  DashboardCategoriesIdEditIndexRoute: DashboardCategoriesIdEditIndexRoute,
  DashboardCitiesIdEditIndexRoute: DashboardCitiesIdEditIndexRoute,
  DashboardPlacesIdEditIndexRoute: DashboardPlacesIdEditIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  SignInIndexRoute: SignInIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
