insert into "amenities" ("id", "name") values (1, 'Wi-Fi');
insert into "amenities" ("id", "name") values (2, 'Free Parking');
insert into "amenities" ("id", "name") values (3, 'Paid Parking');
insert into "amenities" ("id", "name") values (4, 'Wheelchair Access');
insert into "amenities" ("id", "name") values (5, 'Restrooms');
insert into "amenities" ("id", "name") values (6, 'AC');
insert into "amenities" ("id", "name") values (7, 'Outdoor Seating');
insert into "amenities" ("id", "name") values (8, 'Indoor Seating');
insert into "amenities" ("id", "name") values (9, 'Bar Area');
insert into "amenities" ("id", "name") values (10, 'Pet friendly');
insert into "amenities" ("id", "name") values (11, 'Kids'' Play Area');
insert into "amenities" ("id", "name") values (12, 'Drive-Thru');
insert into "amenities" ("id", "name") values (13, 'Loyalty Program');
insert into "amenities" ("id", "name") values (14, '24/7 Service');
insert into "amenities" ("id", "name") values (15, 'Delivery Service');
insert into "amenities" ("id", "name") values (16, 'Vegan');
insert into "amenities" ("id", "name") values (17, 'Live Music');
insert into "amenities" ("id", "name") values (18, 'Private Rooms');
insert into "amenities" ("id", "name") values (19, 'Online Ordering');
insert into "amenities" ("id", "name") values (20, 'EV Charging');
insert into "amenities" ("id", "name") values (21, 'Self-Service');
insert into "amenities" ("id", "name") values (22, 'Smoking');
insert into "amenities" ("id", "name") values (23, 'Guided Tours');
insert into "amenities" ("id", "name") values (24, 'Gift Shop');
insert into "amenities" ("id", "name") values (25, 'Snack Bar');
insert into "amenities" ("id", "name") values (26, 'Information Desk');
insert into "amenities" ("id", "name") values (27, 'Special Exhibitions');
insert into "amenities" ("id", "name") values (28, 'Observation Decks');
insert into "amenities" ("id", "name") values (29, 'ATM');
insert into "amenities" ("id", "name") values (30, 'Photography Area');
insert into "amenities" ("id", "name") values (31, 'A11Y Services');
insert into "amenities" ("id", "name") values (32, 'Study Room');
insert into "amenities" ("id", "name") values (33, 'Romantic Atmosphere');
insert into "amenities" ("id", "name") values (34, 'Family-Friendly');
insert into "amenities" ("id", "name") values (35, 'Concierge Services');
insert into "amenities" ("id", "name") values (36, 'Fitness Facilities');
insert into "amenities" ("id", "name") values (37, 'Spa Services');
insert into "amenities" ("id", "name") values (38, 'Workspaces');
insert into "amenities" ("id", "name") values (39, 'Group Activities');
insert into "amenities" ("id", "name") values (40, 'Eco Friendly');
insert into "amenities" ("id", "name") values (41, 'Public Transportation Access');
insert into "amenities" ("id", "name") values (42, 'Garden');
insert into "amenities" ("id", "name") values (43, 'Complimentary Tasting');
insert into "amenities" ("id", "name") values (44, 'Gaming Stations');
insert into "amenities" ("id", "name") values (45, 'Online Reservation');
insert into "amenities" ("id", "name") values (46, 'Valet Parking');
insert into "amenities" ("id", "name") values (47, 'Catering Services');
insert into "amenities" ("id", "name") values (48, 'Special Dietary Options');
insert into "amenities" ("id", "name") values (49, 'Children''s Menu');
insert into "amenities" ("id", "name") values (50, 'Wine List');
insert into "amenities" ("id", "name") values (51, 'Live Cooking Stations');
insert into "amenities" ("id", "name") values (52, 'Happy Hour Specials');
insert into "amenities" ("id", "name") values (53, 'Chef''s Specials');
insert into "amenities" ("id", "name") values (54, 'Communal Tables');
insert into "amenities" ("id", "name") values (55, 'Brunch Options');
insert into "amenities" ("id", "name") values (56, 'Event Hosting');