[install]
linker = "isolated"
# Only install package versions published at least a day ago
minimumReleaseAge = 86400 # seconds

minimumReleaseAgeExcludes = [
	"typescript",
	"@types/node",
	"@types/bun",
	"tsdown"
]
