# List all available commands
default:
	just --list

# Build the project
@build:
	go build -o main ./main.go

# Setup the project
@setup:
	go mod download
	just env-pull

# Clean the binary
@clean:
	rm -f main

# Live reload
@watch:
	air -c ./.air.toml

# Create .env.example file
@env-example:
	infisical secrets generate-example-env > .env.example

# Pull .env file from Infisical
@env-pull:
	infisical export > .env

# Push .env file to Infisical
@env-push:
	infisical secrets set --file="./.env"
