package cfg

type EnvKey string

// Keep this code block synced with the .env file
const (
	API_AUTH_FACEBOOK_CALLBACK       EnvKey = "API_AUTH_FACEBOOK_CALLBACK"
	API_AUTH_GOOGLE_CALLBACK         EnvKey = "API_AUTH_GOOGLE_CALLBACK"
	API_AUTH_OAUTH_REDIRECT          EnvKey = "API_AUTH_OAUTH_REDIRECT"
	API_AUTH_SESSION_MAX_AGE         EnvKey = "API_AUTH_SESSION_MAX_AGE"
	API_AUTH_SESSION_PATH            EnvKey = "API_AUTH_SESSION_PATH"
	API_AUTH_SIGN_KEY                EnvKey = "API_AUTH_SIGN_KEY"
	API_LOGGER_TYPE                  EnvKey = "API_LOGGER_TYPE"
	API_SEARCH_API_KEY               EnvKey = "API_SEARCH_API_KEY"
	API_SEARCH_SERVER_URL            EnvKey = "API_SEARCH_SERVER_URL"
	API_UPLOAD_PRESIGNED_URL_EXP_MIN EnvKey = "API_UPLOAD_PRESIGNED_URL_EXP_MIN"
	API_URL                          EnvKey = "API_URL"
	DB_HOST                          EnvKey = "DB_HOST"
	DB_NAME                          EnvKey = "DB_NAME"
	DB_PASSWORD                      EnvKey = "DB_PASSWORD"
	DB_PORT                          EnvKey = "DB_PORT"
	DB_TIMEZONE                      EnvKey = "DB_TIMEZONE"
	DB_USER                          EnvKey = "DB_USER"
	DEBUG                            EnvKey = "DEBUG"
	EMAIL_FROM                       EnvKey = "EMAIL_FROM"
	EMAIL_NAME                       EnvKey = "EMAIL_NAME"
	ENV                              EnvKey = "ENV"
	FACEBOOK_CLIENT_ID               EnvKey = "FACEBOOK_CLIENT_ID"
	FACEBOOK_CLIENT_SECRET           EnvKey = "FACEBOOK_CLIENT_SECRET"
	GOOGLE_CLIENT_ID                 EnvKey = "GOOGLE_CLIENT_ID"
	GOOGLE_CLIENT_SECRET             EnvKey = "GOOGLE_CLIENT_SECRET"
	MINIO_AUTOCREATE_BUCKETS         EnvKey = "MINIO_AUTOCREATE_BUCKETS"
	MINIO_ENDPOINT                   EnvKey = "MINIO_ENDPOINT"
	MINIO_LOCATION                   EnvKey = "MINIO_LOCATION"
	MINIO_PASSWORD                   EnvKey = "MINIO_PASSWORD"
	MINIO_USER                       EnvKey = "MINIO_USER"
	PORT                             EnvKey = "PORT"
	REDIS_ADDR                       EnvKey = "REDIS_ADDR"
	REDIS_URL                        EnvKey = "REDIS_URL"
	RUN_MIGRATIONS                   EnvKey = "RUN_MIGRATIONS"
	SMTP_ADDR                        EnvKey = "SMTP_ADDR"
	SMTP_HOST                        EnvKey = "SMTP_HOST"
	SMTP_IDENTITY                    EnvKey = "SMTP_IDENTITY"
	SMTP_PASSWORD                    EnvKey = "SMTP_PASSWORD"
	SMTP_USERNAME                    EnvKey = "SMTP_USERNAME"
	WEB_URL                          EnvKey = "WEB_URL"
)
