// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: addresses.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAddress = `-- name: CreateAddress :one
INSERT INTO addresses (
  country,
  city,
  line1,
  line2,
  postal_code,
  state,
  lat,
  lng
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8
) RETURNING id, country, city, line1, line2, postal_code, state, lat, lng
`

type CreateAddressParams struct {
	Country    string
	City       string
	Line1      string
	Line2      pgtype.Text
	PostalCode pgtype.Text
	State      pgtype.Text
	Lat        float64
	Lng        float64
}

func (q *Queries) CreateAddress(ctx context.Context, arg CreateAddressParams) (Address, error) {
	row := q.db.QueryRow(ctx, createAddress,
		arg.Country,
		arg.City,
		arg.Line1,
		arg.Line2,
		arg.PostalCode,
		arg.State,
		arg.Lat,
		arg.Lng,
	)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.Country,
		&i.City,
		&i.Line1,
		&i.Line2,
		&i.PostalCode,
		&i.State,
		&i.Lat,
		&i.Lng,
	)
	return i, err
}
