// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: amenities.sql

package db

import (
	"context"
)

const createAmenity = `-- name: CreateAmenity :one
INSERT INTO amenities (
  name
) VALUES (
  $1
) RETURNING id, name
`

func (q *Queries) CreateAmenity(ctx context.Context, name string) (Amenity, error) {
	row := q.db.QueryRow(ctx, createAmenity, name)
	var i Amenity
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
