// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: cities.sql

package db

import (
	"context"
)

type CreateCitiesParams struct {
	ID          int32
	Name        string
	StateCode   string
	StateName   string
	CountryCode string
	CountryName string
	ImageUrl    string
	Latitude    float64
	Longitude   float64
	Description string
}

const createCity = `-- name: CreateCity :one
INSERT INTO cities (
  id,
  name,
  state_code,
  state_name,
  country_code,
  country_name,
  image_url,
  latitude,
  longitude,
  description
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10
) RETURNING id, name, state_code, state_name, country_code, country_name, image_url, latitude, longitude, description
`

type CreateCityParams struct {
	ID          int32
	Name        string
	StateCode   string
	StateName   string
	CountryCode string
	CountryName string
	ImageUrl    string
	Latitude    float64
	Longitude   float64
	Description string
}

func (q *Queries) CreateCity(ctx context.Context, arg CreateCityParams) (City, error) {
	row := q.db.QueryRow(ctx, createCity,
		arg.ID,
		arg.Name,
		arg.StateCode,
		arg.StateName,
		arg.CountryCode,
		arg.CountryName,
		arg.ImageUrl,
		arg.Latitude,
		arg.Longitude,
		arg.Description,
	)
	var i City
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StateCode,
		&i.StateName,
		&i.CountryCode,
		&i.CountryName,
		&i.ImageUrl,
		&i.Latitude,
		&i.Longitude,
		&i.Description,
	)
	return i, err
}

const deleteCity = `-- name: DeleteCity :exec
DELETE FROM cities
WHERE id = $1
`

func (q *Queries) DeleteCity(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteCity, id)
	return err
}

const getCities = `-- name: GetCities :many
SELECT id, name, state_code, state_name, country_code, country_name, image_url, latitude, longitude, description FROM cities
`

func (q *Queries) GetCities(ctx context.Context) ([]City, error) {
	rows, err := q.db.Query(ctx, getCities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []City
	for rows.Next() {
		var i City
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StateCode,
			&i.StateName,
			&i.CountryCode,
			&i.CountryName,
			&i.ImageUrl,
			&i.Latitude,
			&i.Longitude,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCityById = `-- name: GetCityById :one
SELECT id, name, state_code, state_name, country_code, country_name, image_url, latitude, longitude, description FROM cities
WHERE cities.id = $1 LIMIT 1
`

func (q *Queries) GetCityById(ctx context.Context, id int32) (City, error) {
	row := q.db.QueryRow(ctx, getCityById, id)
	var i City
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StateCode,
		&i.StateName,
		&i.CountryCode,
		&i.CountryName,
		&i.ImageUrl,
		&i.Latitude,
		&i.Longitude,
		&i.Description,
	)
	return i, err
}

const getFeaturedCities = `-- name: GetFeaturedCities :many
SELECT id, name, state_code, state_name, country_code, country_name, image_url, latitude, longitude, description FROM cities
WHERE id = ANY($1::int[])
`

func (q *Queries) GetFeaturedCities(ctx context.Context, dollar_1 []int32) ([]City, error) {
	rows, err := q.db.Query(ctx, getFeaturedCities, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []City
	for rows.Next() {
		var i City
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StateCode,
			&i.StateName,
			&i.CountryCode,
			&i.CountryName,
			&i.ImageUrl,
			&i.Latitude,
			&i.Longitude,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const randSelectCities = `-- name: RandSelectCities :many
SELECT id
FROM cities
ORDER BY RANDOM()
LIMIT $1
`

func (q *Queries) RandSelectCities(ctx context.Context, limit int32) ([]int32, error) {
	rows, err := q.db.Query(ctx, randSelectCities, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCity = `-- name: UpdateCity :one
UPDATE cities
SET 
  name = $2,
  state_code = $3,
  state_name = $4,
  country_code = $5,
  country_name = $6,
  image_url = $7,
  latitude = $8,
  longitude = $9,
  description = $10
WHERE id = $1
RETURNING id, name, state_code, state_name, country_code, country_name, image_url, latitude, longitude, description
`

type UpdateCityParams struct {
	ID          int32
	Name        string
	StateCode   string
	StateName   string
	CountryCode string
	CountryName string
	ImageUrl    string
	Latitude    float64
	Longitude   float64
	Description string
}

func (q *Queries) UpdateCity(ctx context.Context, arg UpdateCityParams) (City, error) {
	row := q.db.QueryRow(ctx, updateCity,
		arg.ID,
		arg.Name,
		arg.StateCode,
		arg.StateName,
		arg.CountryCode,
		arg.CountryName,
		arg.ImageUrl,
		arg.Latitude,
		arg.Longitude,
		arg.Description,
	)
	var i City
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StateCode,
		&i.StateName,
		&i.CountryCode,
		&i.CountryName,
		&i.ImageUrl,
		&i.Latitude,
		&i.Longitude,
		&i.Description,
	)
	return i, err
}
