// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: countries.sql

package db

import (
	"context"
)

const createCountry = `-- name: CreateCountry :one
INSERT INTO countries (
  id,
  name,
  iso2,
  numeric_code,
  phone_code,
  capital,
  currency,
  currency_name,
  currency_symbol,
  tld,
  native,
  region,
  subregion,
  timezones,
  latitude,
  longitude
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11,
  $12,
  $13,
  $14,
  $15,
  $16
) RETURNING id, name, iso2, numeric_code, phone_code, capital, currency, currency_name, currency_symbol, tld, native, region, subregion, timezones, latitude, longitude
`

type CreateCountryParams struct {
	ID             int32
	Name           string
	Iso2           string
	NumericCode    string
	PhoneCode      string
	Capital        string
	Currency       string
	CurrencyName   string
	CurrencySymbol string
	Tld            string
	Native         string
	Region         string
	Subregion      string
	Timezones      string
	Latitude       float64
	Longitude      float64
}

func (q *Queries) CreateCountry(ctx context.Context, arg CreateCountryParams) (Country, error) {
	row := q.db.QueryRow(ctx, createCountry,
		arg.ID,
		arg.Name,
		arg.Iso2,
		arg.NumericCode,
		arg.PhoneCode,
		arg.Capital,
		arg.Currency,
		arg.CurrencyName,
		arg.CurrencySymbol,
		arg.Tld,
		arg.Native,
		arg.Region,
		arg.Subregion,
		arg.Timezones,
		arg.Latitude,
		arg.Longitude,
	)
	var i Country
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Iso2,
		&i.NumericCode,
		&i.PhoneCode,
		&i.Capital,
		&i.Currency,
		&i.CurrencyName,
		&i.CurrencySymbol,
		&i.Tld,
		&i.Native,
		&i.Region,
		&i.Subregion,
		&i.Timezones,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}
