// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Session struct {
	ID          string
	UserID      string
	SessionData pgtype.Text
	CreatedAt   pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
}

type User struct {
	ID                   string
	Email                string
	Username             string
	FullName             string
	PasswordHash         pgtype.Text
	GoogleID             pgtype.Text
	FbID                 pgtype.Text
	IsEmailVerified      bool
	IsActive             bool
	IsBusinessAccount    bool
	IsVerified           bool
	Role                 string
	PasswordResetToken   pgtype.Text
	PasswordResetExpires pgtype.Timestamptz
	LoginAttempts        pgtype.Int4
	LockoutUntil         pgtype.Timestamptz
	Gender               pgtype.Text
	Bio                  pgtype.Text
	Pronouns             pgtype.Text
	Website              pgtype.Text
	Phone                pgtype.Text
	ProfileImage         pgtype.Text
	BannerImage          pgtype.Text
	FollowersCount       int32
	FollowingCount       int32
	LastLogin            pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}
