package config

const (
	MINIO_ENDPOINT               = "minio.endpoint"
	MINIO_USER                   = "minio.user"
	MINIO_PASSWORD               = "minio.password"
	MINIO_BUCKETS                = "minio.buckets"
	MINIO_LOCATION               = "minio.location"
	MINIO_AUTOCREATE_BUCKETS     = "minio.autocreate-buckets"
	API_LOGGER_TYPE              = "api.logger.type"
	PORT                         = "port"
	ENV                          = "env"
	DB_HOST                      = "db.host"
	DB_NAME                      = "db.name"
	DB_USER                      = "db.user"
	DB_PASSWORD                  = "db.password"
	DB_PORT                      = "db.port"
	DB_TIMEZONE                  = "db.timezone"
	OAUTH_REDIRECT               = "api.auth.oauth.redirect"
	GOOGLE_CLIENT_ID             = "api.auth.google.client-id"
	GOOGLE_CLIENT_SECRET         = "api.auth.google.client-secret"
	GOOGLE_CALLBACK              = "api.auth.google.callback"
	FB_CLIENT_ID                 = "api.auth.facebook.client-id"
	FB_CLIENT_SECRET             = "api.auth.facebook.client-secret"
	FB_CALLBACK                  = "api.auth.facebook.callback"
	AUTH_SIGN_KEY                = "api.auth.sign-key"
	SEARCH_SERVER_URL            = "api.search.server-url"
	SEARCH_API_KEY               = "api.search.api-key"
	REDIS_URL                    = "redis.url"
	REDIS_ADDR                   = "redis.addr"
	AUTH_SESSION_PATH            = "api.auth.session.path"
	AUTH_SESSION_MAX_AGE         = "api.auth.session.max-age"
	UPLOAD_PRESIGNED_URL_EXP_MIN = "api.upload.presigned-url-exp-min"
	WEB_URL                      = "web.url"
	API_URL                      = "api.url"
)
