// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: amenities.sql

package db

import (
	"context"
)

type BatchCreateAmenitiesPoisParams struct {
	AmenityID int32
	PoiID     string
}

const createAmenity = `-- name: CreateAmenity :one
INSERT INTO amenities (
  name
) VALUES (
  $1
) RETURNING id, name
`

func (q *Queries) CreateAmenity(ctx context.Context, name string) (Amenity, error) {
	row := q.db.QueryRow(ctx, createAmenity, name)
	var i Amenity
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const createOneAmenitiesPois = `-- name: CreateOneAmenitiesPois :one
INSERT INTO amenities_pois (
  amenity_id,
  poi_id
) VALUES (
  $1,
  $2
) RETURNING amenity_id, poi_id
`

type CreateOneAmenitiesPoisParams struct {
	AmenityID int32
	PoiID     string
}

func (q *Queries) CreateOneAmenitiesPois(ctx context.Context, arg CreateOneAmenitiesPoisParams) (AmenitiesPoi, error) {
	row := q.db.QueryRow(ctx, createOneAmenitiesPois, arg.AmenityID, arg.PoiID)
	var i AmenitiesPoi
	err := row.Scan(&i.AmenityID, &i.PoiID)
	return i, err
}

const deleteAmenity = `-- name: DeleteAmenity :exec
DELETE FROM amenities
WHERE id = $1
`

func (q *Queries) DeleteAmenity(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteAmenity, id)
	return err
}

const getAllAmenities = `-- name: GetAllAmenities :many
SELECT id, name
FROM amenities
ORDER BY id
`

func (q *Queries) GetAllAmenities(ctx context.Context) ([]Amenity, error) {
	rows, err := q.db.Query(ctx, getAllAmenities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Amenity
	for rows.Next() {
		var i Amenity
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAmenity = `-- name: UpdateAmenity :exec
UPDATE amenities
SET name = $1
WHERE id = $2
`

type UpdateAmenityParams struct {
	Name string
	ID   int32
}

func (q *Queries) UpdateAmenity(ctx context.Context, arg UpdateAmenityParams) error {
	_, err := q.db.Exec(ctx, updateAmenity, arg.Name, arg.ID)
	return err
}
