import { oc } from "@orpc/contract";
import * as dto from "./dto";

export const contract = {
	create: oc.input(dto.createInput).output(dto.createOutput).errors({
		BAD_REQUEST: {},
		UNAUTHORIZED: {},
		FORBIDDEN: {},
		NOT_FOUND: {},
		CONFLICT: {},
		UNPROCESSABLE_CONTENT: {},
		INTERNAL_SERVER_ERROR: {},
	}).route({
		method: 'POST',
		path: '/chats',
		summary: 'Create a new chat',
		description: 'Creates a new chat with the specified participants and settings.',
		successStatus: 201,
		successDescription: 'Created',
		tags: ['Chat'],
	}),
	open: oc.input(dto.openInput).output(dto.openOutput).errors({
		BAD_REQUEST: {},
		UNAUTHORIZED: {},
		FORBIDDEN: {},
		NOT_FOUND: {},
		CONFLICT: {},
		UNPROCESSABLE_CONTENT: {},
		INTERNAL_SERVER_ERROR: {},
	}).route({
		method: 'POST',
		path: '/chats/open',
		summary: 'Open or create a new direct chat',
		description: 'Opens an existing direct chat with the specified user or creates a new one if it does not exist.',
		successStatus: 200,
		successDescription: 'OK',
		tags: ['Chat'],
	}),
	info: oc.input(dto.infoInput).output(dto.infoOutput).errors({
		BAD_REQUEST: {},
		UNAUTHORIZED: {},
		FORBIDDEN: {},
		NOT_FOUND: {},
		CONFLICT: {},
		UNPROCESSABLE_CONTENT: {},
		INTERNAL_SERVER_ERROR: {},
	}).route({
		method: 'GET',
		path: '/chats/:id',
		summary: 'Get chat information',
		description: 'Retrieves information about a specific chat.',
		successStatus: 200,
		successDescription: 'OK',
		tags: ['Chat'],
	}),
	list: oc.input(dto.listInput).output(dto.listOutput).errors({
		BAD_REQUEST: {},
		UNAUTHORIZED: {},
		FORBIDDEN: {},
		NOT_FOUND: {},
		CONFLICT: {},
		UNPROCESSABLE_CONTENT: {},
		INTERNAL_SERVER_ERROR: {},
	}).route({
		method: 'GET',
		path: '/chats',
		summary: 'List chats',
		description: 'Retrieves a list of chats for the authenticated user.',
		successStatus: 200,
		successDescription: 'OK',
		tags: ['Chat'],
	}),
	update: oc.input(dto.updateInput).output(dto.updateOutput).errors({
		BAD_REQUEST: {},
		UNAUTHORIZED: {},
		FORBIDDEN: {},
		NOT_FOUND: {},
		CONFLICT: {},
		UNPROCESSABLE_CONTENT: {},
		INTERNAL_SERVER_ERROR: {},
	}).route({
		method: 'PATCH',
		path: '/chats/:id',
		summary: 'Update chat information',
		description: 'Updates information about a specific chat.',
		successStatus: 200,
		successDescription: 'OK',
		tags: ['Chat'],
	}),
	leave: oc.input(dto.leaveInput).output(dto.leaveOutput).errors({
		BAD_REQUEST: {},
		UNAUTHORIZED: {},
		FORBIDDEN: {},
		NOT_FOUND: {},
		CONFLICT: {},
		UNPROCESSABLE_CONTENT: {},
		INTERNAL_SERVER_ERROR: {},
	}).route({
		method: 'POST',
		path: '/chats/:id/leave',
		summary: 'Leave a chat',
		description: 'Allows a user to leave a specific chat.',
		successStatus: 200,
		successDescription: 'OK',
		tags: ['Chat'],
	}),
	clear: oc.input(dto.clearInput).output(dto.clearOutput).errors({
		BAD_REQUEST: {},
		UNAUTHORIZED: {},
		FORBIDDEN: {},
		NOT_FOUND: {},
		CONFLICT: {},
		UNPROCESSABLE_CONTENT: {},
		INTERNAL_SERVER_ERROR: {},
	}).route({
		method: 'POST',
		path: '/chats/:id/clear',
		summary: 'Clear chat messages',
		description: 'Clears all messages in a specific chat.',
		successStatus: 200,
		successDescription: 'OK',
		tags: ['Chat'],
	}),
	markRead: oc.input(dto.markReadInput).output(dto.markReadOutput).errors({
		BAD_REQUEST: {},
		UNAUTHORIZED: {},
		FORBIDDEN: {},
		NOT_FOUND: {},
		CONFLICT: {},
		UNPROCESSABLE_CONTENT: {},
		INTERNAL_SERVER_ERROR: {},
	}).route({
		method: 'POST',
		path: '/chats/:id/mark-read',
		summary: 'Mark chat messages as read',
		description: 'Marks all messages in a specific chat as read.',
		successStatus: 200,
		successDescription: 'OK',
		tags: ['Chat'],
	}),
	pin: oc.input(dto.pinInput).output(dto.pinOutput).errors({
		BAD_REQUEST: {},
		UNAUTHORIZED: {},
		FORBIDDEN: {},
		NOT_FOUND: {},
		CONFLICT: {},
		UNPROCESSABLE_CONTENT: {},
		INTERNAL_SERVER_ERROR: {},
	}).route({
		method: 'POST',
		path: '/chats/:id/pin',
		summary: 'Pin a chat',
		description: 'Pins a specific chat to the top of the chat list.',
		successStatus: 200,
		successDescription: 'OK',
		tags: ['Chat'],
	}),
	unpin: oc.input(dto.unpinInput).output(dto.unpinOutput).errors({
		BAD_REQUEST: {},
		UNAUTHORIZED: {},
		FORBIDDEN: {},
		NOT_FOUND: {},
		CONFLICT: {},
		UNPROCESSABLE_CONTENT: {},
		INTERNAL_SERVER_ERROR: {},
	}).route({
		method: 'POST',
		path: '/chats/:id/unpin',
		summary: 'Unpin a chat',
		description: 'Unpins a specific chat from the top of the chat list.',
		successStatus: 200,
		successDescription: 'OK',
		tags: ['Chat'],
	}),
	unread: oc.input(dto.unreadInput).output(dto.unreadOutput).errors({
		BAD_REQUEST: {},
		UNAUTHORIZED: {},
		FORBIDDEN: {},
		NOT_FOUND: {},
		CONFLICT: {},
		UNPROCESSABLE_CONTENT: {},
		INTERNAL_SERVER_ERROR: {},
	}).route({
		method: 'POST',
		path: '/chats/:id/unread',
		summary: 'Mark chat messages as unread',
		description: 'Marks all messages in a specific chat as unread.',
		successStatus: 200,
		successDescription: 'OK',
		tags: ['Chat'],
	}),
	mute: oc.input(dto.muteInput).output(dto.muteOutput).errors({
		BAD_REQUEST: {},
		UNAUTHORIZED: {},
		FORBIDDEN: {},
		NOT_FOUND: {},
		CONFLICT: {},
		UNPROCESSABLE_CONTENT: {},
		INTERNAL_SERVER_ERROR: {},
	}).route({
		method: 'POST',
		path: '/chats/:id/mute',
		summary: 'Mute a chat',
		description: 'Mutes notifications for a specific chat.',
		successStatus: 200,
		successDescription: 'OK',
		tags: ['Chat'],
	}),
	unmute: oc.input(dto.unmuteInput).output(dto.unmuteOutput).errors({
		BAD_REQUEST: {},
		UNAUTHORIZED: {},
		FORBIDDEN: {},
		NOT_FOUND: {},
		CONFLICT: {},
		UNPROCESSABLE_CONTENT: {},
		INTERNAL_SERVER_ERROR: {},
	}).route({
		method: 'POST',
		path: '/chats/:id/unmute',
		summary: 'Unmute a chat',
		description: 'Unmutes notifications for a specific chat.',
		successStatus: 200,
		successDescription: 'OK',
		tags: ['Chat'],
	}),
	delete: oc.input(dto.deleteInput).output(dto.deleteOutput).errors({
		BAD_REQUEST: {},
		UNAUTHORIZED: {},
		FORBIDDEN: {},
		NOT_FOUND: {},
		CONFLICT: {},
		UNPROCESSABLE_CONTENT: {},
		INTERNAL_SERVER_ERROR: {},
	}).route({
		method: 'DELETE',
		path: '/chats/:id',
		summary: 'Delete a chat',
		description: 'Deletes a specific chat.',
		successStatus: 200,
		successDescription: 'OK',
		tags: ['Chat'],
	}),
}
