export const amenitiesDisplayNames = new Map<string, string>([
	['wifi', 'Wi-Fi'],
	['freeParking', 'Free Parking'],
	['paidParking', 'Paid Parking'],
	['wheelchair', 'Wheelchair Accessible'],
	['restrooms', 'Restrooms'],
	['ac', 'Air Conditioning'],
	['outdoor', 'Outdoor Seating'],
	['indoor', 'Indoor Seating'],
	['bar', 'Bar'],
	['pet', 'Pet Friendly'],
	['kidsPlay', 'Kids Play Area'],
	['driveThru', 'Drive-Thru'],
	['loyalty', 'Loyalty Program'],
	['allWeekService', '7/24 Service'],
	['delivery', 'Delivery'],
	['vegan', 'Vegan Options'],
	['liveMusic', 'Live Music'],
	['privateRooms', 'Private Rooms'],
	['onlineOrdering', 'Online Ordering'],
	['evCharging', 'EV Charging'],
	['selfService', 'Self Service'],
	['smoking', 'Smoking Area'],
	['guidedTours', 'Guided Tours'],
	['giftShop', 'Gift Shop'],
	['snackBar', 'Snack Bar'],
	['informationDesk', 'Information Desk'],
	['specialExhibitions', 'Special Exhibitions'],
	['observationDecks', 'Observation Decks'],
	['atm', 'ATM'],
	['photographyArea', 'Photography Area'],
	['a11yServices', 'Accessibility Services'],
	['studyRoom', 'Study Room'],
	['romanticAtmosphere', 'Romantic Atmosphere'],
	['familyFriendly', 'Family Friendly'],
	['concierge', 'Concierge'],
	['fitness', 'Fitness Center'],
	['spa', 'Spa'],
	['workspaces', 'Workspaces'],
	['groupActivities', 'Group Activities'],
	['ecoFriendly', 'Eco-Friendly'],
	['publicTransportation', 'Public Transportation'],
	['garden', 'Garden'],
	['complimentaryTasting', 'Complimentary Tasting'],
	['gamingStations', 'Gaming Stations'],
	['onlineReservation', 'Online Reservation'],
	['valetParking', 'Valet Parking'],
	['catering', 'Catering'],
	['specialDietaryOptions', 'Special Dietary Options'],
	['childrensMenu', "Children's Menu"],
	['wineList', 'Wine List'],
	['liveCookingStations', 'Live Cooking Stations'],
	['happyHourSpecials', 'Happy Hour Specials'],
	['chefsSpecials', "Chef's Specials"],
	['communalTables', 'Communal Tables'],
	['brunchOptions', 'Brunch Options'],
	['eventHosting', 'Event Hosting'],
]);
