name: wanderlust

services:
  redis:
    image: redis:alpine
    restart: always
    networks:
      - redisnet
    ports:
      - "6379:6379"

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: wanderlust

  minio:
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ~/minio/data:/data
    environment:
      - MINIO_ROOT_USER=wanderlust
      - MINIO_ROOT_PASSWORD=wanderlust
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"

  typesense:
    image: typesense/typesense:26.0
    restart: on-failure
    ports:
      - "8108:8108"
    volumes:
      - ./typesense-data:/data
    command: "--data-dir /data --api-key=xyz --enable-cors"

networks:
  redisnet:
