name: wanderlust

services:
  wl-postgres:
    container_name: wl-postgres
    image: postgres:16.4-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: wanderlust
    volumes:
      - wl-pg-data:/var/lib/postgresql/data
    shm_size: 1g
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
      start_interval: 1s
    
  wl-pg-bouncer:
    container_name: wl-pg-bouncer
    image: edoburu/pgbouncer:latest
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: wl-postgres
      DB_PORT: 5432
      DB_NAME: wanderlust
      AUTH_TYPE: scram-sha-256
      POOL_MODE: transaction
      MAX_CLIENT_CONN: 100
      DEFAULT_POOL_SIZE: 20
    depends_on:
      wl-postgres:
        condition: service_healthy

  wl-typesense:
    container_name: wl-typesense
    image: typesense/typesense:26.0
    restart: unless-stopped
    ports:
      - 8108:8108
    volumes:
      - wl-typesense-data:/data
    command: "--data-dir /data --api-key=wanderlust --enable-cors"
    networks:
      - wl-searchnet

  wl-typesense-dashboard:
    container_name: wl-typesense-dashboard
    restart: unless-stopped
    ports:
      - 3006:80
    image: ghcr.io/bfritscher/typesense-dashboard:latest
    networks:
      - wl-searchnet

  wl-mailpit:
    image: axllent/mailpit
    container_name: wl-mailpit
    restart: unless-stopped
    volumes:
      - wl-mailpit-data:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  wl-redis:
    image: redis:7.4.0-alpine
    container_name: wl-redis
    restart: unless-stopped
    networks:
      - wl-redisnet
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
      start_interval: 1s

  wl-seaweedfs:
    image: chrislusf/seaweedfs
    container_name: wl-seaweedfs
    restart: unless-stopped
    volumes:
      - wl-seaweedfs-data:/data
    ports:
      - 7333:7333
      - 8333:8333
      - 9333:9333
      - 8888:8888
      - 9340:9340
      - 23646:23646
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=secret
      - S3_BUCKET=default

  wl-jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: wl-jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 16686:16686
      - 4318:4318

networks:
  wl-searchnet:
  wl-redisnet:

volumes:
  wl-pg-data:
  wl-typesense-data:
  wl-mailpit-data:
  wl-seaweedfs-data:
