[api]
port = 5000
url = "http://localhost:5000"

[cache]
grace = "30m"
graceBackoff = "30s"
l1MaxSize = "50mb"

[cors]
allowedOrigins = ["http://localhost:3000"]

[database]
url = "postgresql://postgres:postgres@localhost:5432/wanderlust"
ssl = false

[durable]
id = "wanderlust"
appVersion = "1.0.0"

[email]
from = "Wanderlust <noreply@example.com>"
host = "localhost"
port = 1025
ssl = false
