name: wanderlust

services:
  wl-redis:
    container_name: wl-redis
    image: redis:7.4.0-alpine
    restart: unless-stopped
    networks:
      - wl-redisnet
    ports:
      - ${REDIS_PORT}:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  wl-postgres:
    container_name: wl-postgres
    image: postgres:16.4-alpine
    restart: unless-stopped
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - wl-pg-data:/var/lib/postgresql/data
    shm_size: 1g
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

  wl-minio:
    container_name: wl-minio
    restart: unless-stopped
    ports:
      - ${MINIO_PORT}:9000
      - ${MINIO_CONSOLE_PORT}:9001
    volumes:
      - wl-minio-data:/data
    environment:
      - MINIO_ROOT_USER=wanderlust
      - MINIO_ROOT_PASSWORD=wanderlust
    image: quay.io/minio/minio
    command: server /data --console-address ":${MINIO_CONSOLE_PORT}"

  wl-typesense:
    container_name: wl-typesense
    image: typesense/typesense:26.0
    restart: unless-stopped
    ports:
      - ${TYPESENSE_PORT}:8108
    volumes:
      - wl-typesense-data:/data
    command: "--data-dir /data --api-key=${TYPESENSE_API_KEY} --enable-cors"
    networks:
      - wl-searchnet

  wl-typesense-dashboard:
    container_name: wl-typesense-dashboard
    restart: unless-stopped
    ports:
      - ${TYPESENSE_DASHBOARD_PORT}:80
    image: ghcr.io/bfritscher/typesense-dashboard:latest
    networks:
      - wl-searchnet

  wl-mailpit:
    image: axllent/mailpit
    container_name: wl-mailpit
    restart: unless-stopped
    volumes:
      - wl-mailpit-data:/data
    ports:
      - ${MAILPIT_PORT}:8025
      - ${MAILPIT_SMTP_PORT}:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  wl-asynqmon:
    container_name: wl-asynqmon
    image: hibiken/asynqmon
    restart: unless-stopped
    networks:
      - wl-redisnet
    ports:
      - ${ASYNQMON_PORT}:8080
    environment:
      REDIS_URL: redis://wl-redis:${REDIS_PORT}
    depends_on:
      - wl-redis

  wl-otel-lgtm:
    container_name: wl-otel-lgtm
    restart: unless-stopped
    ports:
      - ${GRAFANA_PORT}:3000
      - ${OLGTM_GRPC_PORT}:4317
      - ${OLGTM_HTTP_PORT}:4318
    tty: true
    stdin_open: true
    image: grafana/otel-lgtm

networks:
  wl-redisnet:
  wl-searchnet:

volumes:
  wl-pg-data:
  wl-minio-data:
  wl-typesense-data:
  wl-mailpit-data:
