name: wanderlust

services:
  wl-redis:
    container_name: wl-redis
    image: redis:7.4.0-alpine
    restart: always
    networks:
      - wl-redisnet
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  wl-postgres:
    container_name: wl-postgres
    image: postgres:16.4-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: wanderlust
    volumes:
      - wl-pg_data:/var/lib/postgresql/data
    shm_size: 1g
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

  wl-minio:
    container_name: wl-minio
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./tmp/minio/data:/data
    environment:
      - MINIO_ROOT_USER=wanderlust
      - MINIO_ROOT_PASSWORD=wanderlust
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"

  wl-typesense:
    container_name: wl-typesense
    image: typesense/typesense:26.0
    restart: always
    ports:
      - "8108:8108"
    volumes:
      - ./tmp/typesense-data:/data
    command: "--data-dir /data --api-key=wanderlust --enable-cors"
    networks:
      - wl-searchnet

  wl-typesense-dashboard:
    container_name: wl-typesense-dashboard
    restart: always
    ports:
      - 3006:80
    image: ghcr.io/bfritscher/typesense-dashboard:latest
    networks:
      - wl-searchnet

  wl-inbucket:
    container_name: wl-inbucket
    restart: always
    ports:
      - 10000:9000
      - 2500:2500
      - 1100:1100
    image: inbucket/inbucket

  wl-asynqmon:
    image: hibiken/asynqmon
    restart: always
    networks:
      - wl-redisnet
    ports:
      - "8080:8080"
    environment:
      REDIS_URL: redis://wl-redis:6379
    depends_on:
      - wl-redis

  wl-openobserve:
    container_name: wl-openobserve
    restart: always
    volumes:
      - ./tmp/zodata:/data
    environment:
      - ZO_DATA_DIR=/data
      - ZO_ROOT_USER_EMAIL=wanderlust@example.com
      - ZO_ROOT_USER_PASSWORD=wanderlust
    ports:
      - 5080:5080
    image: public.ecr.aws/zinclabs/openobserve:latest

networks:
  wl-redisnet:
  wl-searchnet:

volumes:
  wl-pg_data:
