default:
  just --list

# Live reload
@watch:
  pnpm dev

# Setup the project
@setup:
  echo "=> Setting up the project..."
  pnpm install
  echo "=> Setup completed. Run 'just watch' to start the server."

# Type generation
[confirm('Is API up and running? [y/N]')]
@typegen:
  echo "=> Generating types..."
  pnpm run openapi
  echo "=> Type generation completed"